API:
  APIKEY: null
  HOST: api.ndif.us
  SSL: true
  ZLIB: true
APP:
  CACHE_DIR: ~/.cache/nnsight/
  DEBUG: false
  REMOTE_LOGGING: true
  PYMOUNT: true
  CROSS_INVOKER: true
  TRACE_CACHING: false
