API:
  APIKEY: null
  FORMAT: json
  HOST: ndif.dev
  JOB_ID: null
  SSL: true
  ZLIB: true
APP:
  DEBUG: true
  FRAME_INJECTION: true
  CONTROL_FLOW_HANDLING: true 
  LOGGING: false
  REMOTE_LOGGING: true
